hwi_oauth:
    firewall_names: [secured_area]
    resource_owners:
        auth0:
            type:                oauth2
            class:               'App\Auth0ResourceOwner'
            client_id:           "%env(AUTH0_CLIENT_ID)%"
            client_secret:       "%env(AUTH0_CLIENT_SECRET)%"
            base_url:            "https://%env(AUTH0_DOMAIN)%"
            scope: "openid profile"
    http:
        client: httplug.client.hwi_special # Then you specify the special service to use.

httplug:
    clients:
        default:
            factory: 'httplug.factory.curl'
        hwi_special:
            factory: 'httplug.factory.guzzle6'
            config: # You pass here the Guzzle configuration, exactly like before.
                timeout: 10
                verify: false
                max_redirects: 1
                ignore_errors: false